# Code generated by using Codegen.
# command to run: playwright codegen https://validaciones.rodrigovillanueva.com.mx/Radios_Ok.html

from playwright.sync_api import Playwright, sync_playwright, expect


def test_codegen(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False, slow_mo = 500, args=["--start-maximized"])
    context = browser.new_context() # record_video_dir="Playwright/Exercises/videos/checkbox2"
    page = context.new_page()
    page.goto("https://validaciones.rodrigovillanueva.com.mx/Radios_Ok.html")
    page.get_by_role("textbox", name="Nombre").click()
    page.get_by_role("textbox", name="Nombre").press("CapsLock")
    page.get_by_role("textbox", name="Nombre").fill("Luis Hernandez")
    page.locator("#miFormulario div").filter(has_text="Telefono").click()
    page.get_by_role("textbox", name="Telefono").click()
    page.get_by_role("textbox", name="Telefono").fill("5511223344")
    page.get_by_role("radio", name="Opción 2").check()
    page.get_by_role("checkbox", name="Opción B").check()
    page.get_by_role("checkbox", name="Opción A").check()
    page.get_by_role("button", name="Enviar").click()
    expect(page.get_by_text("Formulario enviado correctamente")).to_be_visible()

    page.screenshot(path="Playwright/Exercises/screenshots/checkbox2.png")

    # ---------------------
    context.close()
    browser.close()

with sync_playwright() as playwright:
    test_codegen(playwright)
